"""
Notification Model
==================

Stores notification records for system events, alerts,
and messages to users.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from backend.models.base import Base, TimestampMixin, generate_uuid


class Notification(Base, TimestampMixin):
    """
    A notification or alert generated by the system.
    
    Attributes:
        id: Unique notification identifier (UUID).
        title: Short notification title.
        message: Full notification message.
        severity: Notification severity (info, warning, error, critical).
        category: Notification category (collection, change, security, system).
        source: What generated this notification.
        target_user_id: Specific user to notify (null = all admins).
        is_read: Whether the notification has been read.
        read_at: When the notification was read.
        is_sent: Whether email/external notification was sent.
        sent_at: When the external notification was sent.
        server_id: Related server (if applicable).
        link: URL or path to related resource.
    """
    
    __tablename__ = "notifications"
    
    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=generate_uuid
    )
    title: Mapped[str] = mapped_column(
        String(200), nullable=False
    )
    message: Mapped[str] = mapped_column(
        Text, nullable=False
    )
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False, default="info", index=True
    )
    category: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True
    )
    source: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True
    )
    target_user_id: Mapped[Optional[str]] = mapped_column(
        String(36), nullable=True, index=True
    )
    is_read: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False, index=True
    )
    read_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    is_sent: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )
    sent_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    server_id: Mapped[Optional[str]] = mapped_column(
        String(36), nullable=True, index=True
    )
    link: Mapped[Optional[str]] = mapped_column(
        String(500), nullable=True
    )
    
    def __repr__(self) -> str:
        return f"<Notification(title={self.title}, severity={self.severity})>"
